### ISSUE TITLE
Bug: thumbprint should be thumbprints

### ISSUE THREAD

**Issue by autodidacticon** [GoCarrot/terraform-aws-circleci_oidc#1]
https://github.com/GoCarrot/terraform-aws-circleci_oidc/blob/01dced3d43e6d2222ea6617c2a6ab9b31ea07327/main.tf#L39

**Comment by AlexSc** [comment]
Is this causing a problem?

If memory serves me, I put this in place because otherwise terraform would show permanently show a drift, but no guarantees I am recalling correctly and of course one of HashiCorp or AWS could have addressed that.

**Comment by autodidacticon** [comment]
`var.thumbprint` is not declared; it should be `var.thumbprints` to match the declaration in `variables.tf`

Additionally, `thumbrint` should be `thumbprint`.

**Comment by AlexSc** [comment]
Ah, got it! Thank you! That's what I get for turning something from our infrastructure into a module but not going back and using the module ;) Fixed in 0.1.1: https://registry.terraform.io/modules/GoCarrot/circleci_oidc/aws/0.1.1
